### ISSUE TITLE
questions/ modifications to herring Tables 1 and 2

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#10]
Question: Is the order of the tables determined by the order in which they are cited in the text, or set in latex?

Table 1, 2- can you confirm these are 90%iles
Table 2- can you please modify into two tables:
1) col headers: Stock | Model | SB0 | 0.30*SB0 | Lower | Median | Upper
2) col headers: Stock | Model | SB2018 | Proportion age 3 in 2018 | Proportion age 4+ in 2018
*cols 4 and 5 to include Lower | Median | Upper (90th percentiles)

**Comment by jaclyncleary** [comment]
where the Proportion age 3 in 2018 and Proportion age 4+ in 2018 values come from PropAge3 and PropAge4to10 in the iscammcmc_proj_Gear1.csv

**Comment by grinnellm** [comment]
Just saw this again -- not sure if still need an answer. Table order is determined by the order in which they are set in latex.

**Comment by jaclyncleary** [comment]
thanks
