### ISSUE TITLE
Matt, I can't fetch your commits in the Herring repo

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/csas-latex#100]
I think it's a permissions thing, maybe you could add me as a collaborator.. I can't catch up to you until I get access.. I posted an issue in the Herring repo but I'm not sure if you can even see it.

**Comment by grinnellm** [comment]
I just added you to mine. It's actually Sarah's originally -- will that work?

**Comment by cgrandin** [comment]
I don;t think so... it's https://github.com/grinnellm/Herring/ right?

**Comment by grinnellm** [comment]
Yes, that's mine. Sarah is the owner.

**Comment by cgrandin** [comment]
That invite did the trick.. now I can try to find out what's with the decision tables

**Comment by grinnellm** [comment]
Perfect. Sorry for the delay.
I just coped the new model folders from the private repo, did a `delete.rdata.files()`, and `build()`, and my decision tables still look the same.

**Comment by cgrandin** [comment]
Me too.. Somehow it reverted back to using the old column 03B0 which was based on bo from iscam. I need to fix this. i did it once already but somehow it got rewound.
Anyway I think this is good news

**Comment by jaclyncleary** [comment]
so by "good news" we can trust that matt's (and my) decision tables are the most up-to-date?

**Comment by grinnellm** [comment]
Great news that you found the bug! So weird that it got reverted to the old version. Was probably last Friday (the 13th)?

**Comment by cgrandin** [comment]
I looked and see that I actually changed the iscam output code to put sbo * 0.3 to the 03B0 column on October 11 (commit a3f8a0f1).

So I think that it's still going to be the higher numbers in the decision tables... I am pretty sure we re-ran the mcevals after I did that right?? It does make sense though, since the sbo estimates are higher than the bo estimates were. I think you had the old bo version.

**Comment by cgrandin** [comment]
I've confirmed that we are at the higher values for the decision tables.. This makes little analytical sense, so I'd like to spend time tomorrow going through this.. Comparing files etc. In the meantime if you focus on the SAR and give me a chance to try to tease this out that would be great.

**Comment by jaclyncleary** [comment]
We'll focus on the SAR and touch base on decision tables again in the morning. thanks Chris.

**Comment by cgrandin** [comment]
Thanks Jaclyn
