### ISSUE TITLE
Herring SAR

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#101]
Matt- post update when you've added the following to the SAR:
-Decision tables (AM1 and AM2)
-Production analysis plots- panels (a) and (c) --Include AM2 only for now

**Comment by jaclyncleary** [comment]
I asked FM which tables they USE from the SR/SARs, and they would like to see:
-Table with recent 5-6 years of SB (median +CIs). We could include a condensed version of Table 18.
--> something like Table 2: http://waves-vagues.dfo-mpo.gc.ca/Library/364435.pdf

And something like Table 3 (same link) -- but with columns: Stock, SB_2017, SB0, 0.30SB0, depletion (SB_2017/SB0)

*I think that for these, we could put in the old format/ data and then say: is this what you want...

Open to other suggestions!!

**Comment by jaclyncleary** [comment]
I will focus on bullets and text (so don't change those sections- that way I can copy/ paste into your version of the SAR.

**Comment by grinnellm** [comment]
I'll start with the production figures. Any ideas on how to put the tables in? It'll take a while to write them out by hand, and if we end up changing them tomorrow.. that'll be depressing to have to do it again.

**Comment by jaclyncleary** [comment]
I think we add in the production figures.
Then for the tables, we include a bulleted list of the type of info we can include, and then we can figure out how best to present this (and work on this Fri/ Mon...). I definitely don't want to do this by hand, and, I think that because CSAS is concerned about space/ #pages, that we'll have to be creative.

**Comment by grinnellm** [comment]
Ok, sounds good. So what would you like me to do tonight? I've put in the depletion figures for AM2.

**Comment by grinnellm** [comment]
I put in a link to those tables, and bullets that summarise what they contain (p19). I'll attach my copy of the SAR here. Notice that the figure numbers are automated and x-referenced, so please try to not break them if you cut and paste them into your version:) Might be best to cut and paste from your version to mine?
[Pacific Herring draft SAR with depletion figs.docx](https://github.com/cgrandin/csas-latex/files/1393512/Pacific.Herring.draft.SAR.with.depletion.figs.docx)

**Comment by jaclyncleary** [comment]
This is great. I'll cut and paste my text into your version. I'll post here and email when done. 
Sarah will read the text in the AM.
I'll add a list of "tabular" info to include (incl. decision tables).
Bonne nuit! See you in the morning.

**Comment by grinnellm** [comment]
See you tomorrow. I'll try to be there at 8:30. Get some sleep:) You did great today!

**Comment by jaclyncleary** [comment]
Matt/ Sarah- same comments send by email.

[Pacific.Herring.draft.SAR.18Oct17.docx](https://github.com/cgrandin/csas-latex/files/1393913/Pacific.Herring.draft.SAR.18Oct17.docx)

Matt- I added my text to your version so there shouldn’t be any changes to figures. I left bullets in to remind us to have a discussion about required ‘tabular’ info.

Sarah- please read though the Summary bullets and the HG and PRD summaries. I decided not to populate the info for the other 3 stocks until we have consensus on the type of info.
Also the yellow text is where I’d appreciate your less-tired eyes to make sure I’ve captured the outcomes correctly.
