### ISSUE TITLE
Table 2. edits

### ISSUE THREAD

**Issue by Shawkshaw** [cgrandin/csas-latex#102]
Do we need to remove the "survey" column and the second row from Table 2?  Similar to edits to Table 48.

**Comment by jaclyncleary** [comment]
yes, for final WP

**Comment by cgrandin** [comment]
Actually the priors are different so I don't think so..

**Comment by jaclyncleary** [comment]
I see what you mean. It's a bit ugly but I think not worth fiddling with and I suggest leaving as-is.

**Comment by Shawkshaw** [comment]
Yeah there is just a repeat row for both AM1 and AM2...Makes it look like we did more work than we did:)
