### ISSUE TITLE
Tables 13 to 17 have incorrect values for SB_2018

### ISSUE THREAD

**Issue by grinnellm** [cgrandin/csas-latex#103]
It looks to me like the values for the row SB_2018 are incorrect. I think they're calculated using projected SB under all the potential TAC values, whereas they should be calculated using only the zero-catch scenarios. For example, HG AM2 (Table 13) should be:
1.900, 4.346, 11.326 (5%, 50%, and 96%)
instead of 
0.766 3.270 10.219.
I'm not sure if this also applies to the rows for age-3 and age-4 to -10? 
My apologies if I'm out to lunch here.. it's been a long few weeks.
![image](https://user-images.githubusercontent.com/25674027/31844298-a3f9f850-b5ac-11e7-9546-5f7707372448.png)

**Comment by jaclyncleary** [comment]
I took a look and I think that what's happening is that the quantiles for SB_2018 are being calculated across all SB_2018 values in the iscammcmc_proj_Gear1.csv, whereas the quantiles **should only** be calculated across runs where TAC=0.0 (reflecting pre-fishery SB).  I think this is happening in make.ref.points.table() in csas-latex/doc/r/r-functions, but I'm not 100% sure...

**Comment by cgrandin** [comment]
I'm here today and going through all the issues.

**Comment by cgrandin** [comment]
Ok, I have fixed the problem. You will unfortunately have to do the

`source("all.r");delete.rdata.files();build()`

again

**Comment by jaclyncleary** [comment]
With the correct table values, any idea as to why the 2018 forecast for SOG AM2 go up from estimated SB_2017 (114.626 to 125.285), but goes down slightly for AM1 (175.962 to 169.910)?

**Comment by grinnellm** [comment]
Not sure -- I see that M for AM2 is decreasing, but it's increasing for AM1.

**Comment by jaclyncleary** [comment]
Thanks. I'll take a closer look tonight.

**Comment by jaclyncleary** [comment]
I agree, the directional difference in M between AM1 and AM2 explains the difference. There's no difference in recruitment patterns.
