### ISSUE TITLE
edit to AM1 decision tables 

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#104]
the column with fixed cutoff, e.g., HG: P(SB2018 < 10, 700), is not applied for the **AM1** model.
From the meeting, managers requested this column either be deleted or filled with NAs for **AM1**.

Also, pls comment-out 5% HR column

**Comment by cgrandin** [comment]
Should I remove the P(U2018 > 5%) column for both AM2 and AM1? I can't recall if it was just AM1 or both.

**Comment by cgrandin** [comment]
I made the commit, but not sure about the 5% so I'll leave open.

**Comment by grinnellm** [comment]
What was the verdict for the 5% HR column? It's still there. I can remove it -- do you want it removed for both AM2 and AM1?

**Comment by jaclyncleary** [comment]
remove for both AM1 and AM2 pls
