### ISSUE TITLE
edits to decision tables - catch stream

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#105]
Sarah: We need the catch levels associated with 50% probability of exceeding the 10% and 20% harvest rates for each stock.

The only way I know to "find" these TAC levels is to run the -mceval with small increments in TAC (in the pfc file) and then look to see which TAC value corresponds to the 50% prob value.  If you look at the decision tables from 2016 you'll see there isn't a smooth transition between TAC values.

Chris might have some other suggestions... or some code to "thin" the resulting decision table.

**Comment by cgrandin** [comment]
That's the way we do it for Hake, it's a pain but the only way I know of.

**Comment by Shawkshaw** [comment]
Should I start by set the tac vectors in the pfc files to the same as the 2016 vectors.  
I thought that I had but looking at them now they are different...

**Comment by jaclyncleary** [comment]
no. I'll post a spreadsheet with TAC vector for each stock. give me a sec.

**Comment by jaclyncleary** [comment]
This attached shows how I would narrow down the TAC for HG AM2. I basically look for the TAC nearest to the 50% prob levels, then use small increments between numbers to find the TAC == 50% probability of 10% and 20% HR. Give this first one a try and see if you have questions.

[revised.decision.tables.23Oct17.xlsx](https://github.com/cgrandin/csas-latex/files/1408596/revised.decision.tables.23Oct17.xlsx)

**Comment by Shawkshaw** [comment]
Got it:)  Should I rerun the 5M mcmcs?

**Comment by jaclyncleary** [comment]
all you have to do is change the pfc file (update the catch stream) and then run the -mceval

**Comment by grinnellm** [comment]
Let's try to automate this for next year..

**Comment by jaclyncleary** [comment]
note- the for the final decision tables, there should be ~10 TAC rows

**Comment by Shawkshaw** [comment]
OKay good, I will finish these tonight and send you an spreadsheet of what I think the vectors should be.

**Comment by Shawkshaw** [comment]
Should the catch streams be the same for AM1 and AM2 I noticed in 2016 they matched?

**Comment by jaclyncleary** [comment]
Yes. Easiest is to figure out the 50p levels for 10% and 20% HR for AM1 and AM2, separately, and then add those "2" AM1 TAC levels to the AM2 pfc (and vice versa).

**Comment by Shawkshaw** [comment]
[New catch streams_SH.xlsx](https://github.com/cgrandin/csas-latex/files/1412763/New.catch.streams_SH.xlsx)

These are the new catch streams I came up with.  Let me know if you want to see any changes and I will load these into the Herring repo.

**Comment by jaclyncleary** [comment]
these look great. tedious eh?

**Comment by Shawkshaw** [comment]
Great, I uploaded these new runs into the Herring repo.  Once you fetch/merge you have to replace the models folder/ source(ResearchDocumentV2.R)/ source(all.r)/delete.rdata.files()/build()

**Comment by grinnellm** [comment]
I get weird table 33 (HG AM2): way too many rows.

**Comment by grinnellm** [comment]
![image](https://user-images.githubusercontent.com/25674027/32015114-f83b1fea-b974-11e7-82fc-ed8c9c2132d3.png)

**Comment by Shawkshaw** [comment]
It did not get updated properly...I am updating now and will push asap

**Comment by Shawkshaw** [comment]
They should be up to date on the herring repo now

**Comment by grinnellm** [comment]
The new data gives me an error when I `build()`:
> create.rdata.file: No RData file found in ../../models/HG/AM1. Creating one now.
> Error in t.default(r.quants) : argument is not a matrix

I'm guessing, but this may have something to do with the `proj` file.. I got this message when I merged your new files:

> C:\Grinnell\Workspace\Herring\Herring [master =]> git fetch Shawkshaw
> remote: Counting objects: 46, done.
> remote: Total 46 (delta 27), reused 27 (delta 27), pack-reused 19
> Unpacking objects: 100% (46/46), done.
> From https://github.com/Shawkshaw/Herring
>    486ce79f..b6d58f05  master     -> Shawkshaw/master
> C:\Grinnell\Workspace\Herring\Herring [master =]> git merge Shawkshaw/master
> Merge made by the 'recursive' strategy.
> fatal: unable to generate diffstat for 2017mcmc/models/HG/AM1/iscammcmc_proj_Gear1.csv

**Comment by cgrandin** [comment]
I'll also look at this..

**Comment by Shawkshaw** [comment]
I think we resolved it now...I had the wrong folder for HG AM1:) 
Let me know if it working for you though

**Comment by cgrandin** [comment]
Everything seems to work fine for me after all the model and doc code updates.
