### ISSUE TITLE
Figure caption for Figure 20

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#107]
It looks like the figure has been changed to use heat-colours, with darkest circles as most recent, and that the triangle is now terminal year and the 'x' is intersection of SB0, and unfished age-2 recruitment, R0.

Please take a look and adjust the caption to match. And maybe the triangle could be filled with white- it's hard to see for CC. Thanks!

**Comment by grinnellm** [comment]
Done.
