### ISSUE TITLE
Odd SB_2018 for CC AM2 with new data/code

### ISSUE THREAD

**Issue by grinnellm** [cgrandin/csas-latex#108]
![ssb2018](https://user-images.githubusercontent.com/25674027/32014234-5c015722-b972-11e7-8af0-5b92040e7f13.png)

**Comment by grinnellm** [comment]
The figure for SB_2017 has a similar odd panel for CC AM2, but not as pronounced. The tails still appear to be cut off, and the distribution appears to be bimodal-ish.

**Comment by jaclyncleary** [comment]
Can you plot SB_2017 and SB_2018 for CC AM2 on the plot? I think it's the scale.

**Comment by jaclyncleary** [comment]
Can you plot SB_2017 and SB_2018 for CC AM2 on the plot? I think it's the scale.

**Comment by grinnellm** [comment]
Hmm, ok I found the problem. The `proj` file for CC AM2 only has 94 rows for TAC==0 (instead of 5,000). The same for `iscam_sbt_mcmc.csv`. Maybe others?

**Comment by jaclyncleary** [comment]
Hmm. The number of rows in iscammcmc_proj_Gear1.csv file depends on the #TAC values. It should always be 5,000 (the thinned chain) * length(TAC). So for CC AM2, nrows= 55,000 (5,000*11), with the posterior distribution for SB_2018 (given catch=0) calculated over 5,000 values.

I just updated github/Herring and I see that CC AM2 has only 1219 rows, so something is wrong with this file. I do not see this in any of the other 9 files. @Shawkshaw Can you please take a look?

**Comment by Shawkshaw** [comment]
I updated CC AM2 so it now has 65000 rows in the iscammcmc_proj_Gear1.csv file and I am checking the others.

**Comment by Shawkshaw** [comment]
CC and PRD have 650000 rows and HG/SOG/WCVI all have 60000 rows...I am trying to ID why

**Comment by Shawkshaw** [comment]
CC and PRD have 13 values in the TAC catch streams and the others all have only 12 this leads to the difference!

**Comment by grinnellm** [comment]
So we're good? I can copy/paste the decision tables into Word (which I'll put in the SAR when you're done, Sarah)?

**Comment by Shawkshaw** [comment]
Fetch and merge the latest updates for CC AM2 and HG AM1 from the herring repo and this should be correct..

**Comment by Shawkshaw** [comment]
Matt, you can copy and paste them in to the current version of the SAR.  Let me know when you are complete and I in the meantime I will continue working on the text on a copy.

**Comment by grinnellm** [comment]
Done!
