### ISSUE TITLE
modification to Table 3

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#11]
Table 3. Estimated and fixed parameters and prior...

row 6: change to "Variance ratio, rho (<symbol>)"
row 7: change to: "Inverse total variance, kappa (<symbol>)" 
row 8: **remove** row "Survey age 50% selectivity" - we don't use this
row 9: change to: "Fishery age at 50% logistic selectivity (<symbol>)
row 10: **remove** row "Survey SD of logistic selectivity" - we don't use this

q-priors - remove from this table and include separate (new) table to show q priors for AM1 and AM2 (from ctl files)

note : With the q-prior removed, this table is the same for all 5 stocks and AM1 and AM2.  Can we consolidate to 1-table and reflect this in the header?

**Comment by cgrandin** [comment]
No problem to do all that.

The number of estimated parameters in each model is different so there are differences between tables. If you don't care about showing those I could delete that column and make it one table..

**Comment by cgrandin** [comment]
Or I should say only the log fishing mortality values are different..

**Comment by jaclyncleary** [comment]
right... and the log F-mortality values differ by stock because of the number of years for each gear differs.  I don't think we need to report the log fishing mortality values so we can simplify to one table :)

**Comment by cgrandin** [comment]
Ok, sounds good

**Comment by cgrandin** [comment]
Done in commit dec1bb21fde9cd97a34b68f857e03c324cd5b8ee
