### ISSUE TITLE
I added the first two pages but..

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/csas-latex#110]
you need to add a few packages and I had major trouble with MikTex so here's how you do it in Windows:
[localtexmf.zip](https://github.com/cgrandin/csas-latex/files/1423092/localtexmf.zip)

Make a folder called c:\localtexmf which holds the unzipped contents of this zip file.
Open MikTex Settings (Admin)
In the Roots tab, add the path c:\localtexmf
In the General tab, click Refresh FNDB

That will install all the packages and you should now be able to build the complete doc.

**Comment by grinnellm** [comment]
This is great! Thanks Chris.

**Comment by Shawkshaw** [comment]
Chris, I am following your steps but receiving an error when trying to add the path to the Roots tab:
"Not a TDS-compliant root directory"
Any ideas?

**Comment by cgrandin** [comment]
That means you have the folder structure wrong.. there should only be one localtexmf directory, not one embedded in another one if that's the issue due to the way you unzipped it ?

**Comment by Shawkshaw** [comment]
Thanks Chris! 
I had the whole zip file in the localtexmf directory...
