### ISSUE TITLE
How/where do I rename columns (i.e., decision tables)?

### ISSUE THREAD

**Issue by grinnellm** [cgrandin/csas-latex#111]
I've looked around, but I don't see where you specify the column names for probabilistic decision tables.

**Comment by cgrandin** [comment]
It's in load-models.r in the function calc.probabilities()

**Comment by cgrandin** [comment]
If you change them you'll need to do the whole source("all.r");delete.rdata.files();build()
again after

**Comment by cgrandin** [comment]
To test that, just delete one of the rdata files manually and then do build() to rebuild just that one

**Comment by grinnellm** [comment]
Thanks, that's perfect. One more thing.. column alignment: how do set the first column (TAC) flush-right?

**Comment by grinnellm** [comment]
Nevermind, I think I found it: `align = get.align(ncol(tab))`
