### ISSUE TITLE
How to edit the 'Reference points' table header?

### ISSUE THREAD

**Issue by grinnellm** [cgrandin/csas-latex#115]
I want to change the second `\toptule` to `\cmidrule(lr){2-4} \cmidrule(lr){5-7}`. I looked in `calc.mcmc`, and `make.ref.points.table`, which is where I thought it might be..
![image](https://user-images.githubusercontent.com/25674027/32517126-5281d058-c3ba-11e7-9126-156aaea15b90.png)

**Comment by cgrandin** [comment]
Done, but I'll do the spawning biomass/depletion ones as well. I had planned to do this anyway!
