### ISSUE TITLE
Table 5

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#12]
Chris: a couple of edits please to Table 5 (_Posterior 5th percentile, median, 95th percentile) and MPD estimates of key parameters..._): I think it makes sense for the list of estimated parameter values in Table 5 to be the same as the parameters listed in Table 3 (Ro, Steepness, M, Rbar, Rinit_bar, rho, kappa, **sigma, tau,** q1, q2)- also matches Fig17 (Prior probability distributions and posterior histograms) Thanks, ~J

*note we may need to calculate **sigma and tau**. Let me know...

**Comment by cgrandin** [comment]
I'm working on this - almost done

**Comment by cgrandin** [comment]
Done in commit 59f60c2bda1db3cb499c5fe74b4ee6443cf78179. I did have to calculate sigma and tau but already had a function to do it so that was nice.
