### ISSUE TITLE
Table 7 (Posterior and MPD estimates of spawning biomass...)

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#13]
Couple edits:

-please change percentiles to 5th, 50th, and 95th. (it was a past herring subcommittee decision to report 90th credible intervals, not 95th) 
-I compared the spawning biomass values to the 2016 assessment and they are very similar, with the exception of the last couple years (I will investigate this).
-Please remove the 2018 projection year from the table (the final row)
-Table header: please change "relative spawning biomass" to **"Depletion (sbt/sbo)"**
-The depletion values (percentiles)... these are puzzling. Please check the calculation- should be sbt/ sbo (not bo)
-the MPD and median sbt values match :)
-the MPD and median depletion values do not match...

**Comment by cgrandin** [comment]
I'm working on this

**Comment by grinnellm** [comment]
I have updated my figures and captions to show 90% CIs -- those are both set by the variable `ciLevel` in "ResearchDocumentV2.R".
I tried to update the CIs for the tables in the csas-latex template part by updating the variable `mcmc.ci` in "custom-knitr-variables.r", and `confidence.vals` in "model-setup.r". This didn't seem to do as I expected. Or at least, the column headers in the tables were not updated. But I see now that you're working on this, so maybe you've already updated your CIs?

**Comment by grinnellm** [comment]
Thanks Chris!

**Comment by cgrandin** [comment]
I've also updated my code to use 90% CIs. That is set in model-setup.r `confidence.vals <- c(0.05, 0.95)
` The amount of things that I'm changing means you need to `delete.rdata.files();build()` each time you fetch my stuff and that's when those calculations are done.

**Comment by cgrandin** [comment]
We are not outputting sbo in the mcmc files. So we'd have to do that and re-run all models -mceval step.
So I'll go back to iscam-pbs and see if I can add that.

**Comment by cgrandin** [comment]
I added sbo to iscam-pbs mcmc outputs. You can merge it and try it out. I am seeing the same values though
i.e. bo = sbo
so that's not the issue.

**Comment by cgrandin** [comment]
My bad! I was dividing bt/bo for the MPD depletion instead of sbt/sbo. Fixed it in commit b2a425c5a58980d63d3b035733571dca74ed88df. So I'm going to revert iscam-pbs and you don't need to do anything there. Whew, we don't need to re-run any models again.

**Comment by jaclyncleary** [comment]
great!

b0 and sb0 in the rep file and mcmc outputs should be different values though because sbo is calculated using longterm average weight-age and maturity-age, whereas bo uses the 'years' specified in the pfc file - which for herring is the 5-year recent average weight-age and maturity-age.
Can you confirm this is what you are seeing in the outputs?

**Comment by cgrandin** [comment]
Yes, they are different in the REP file. sbo seems to be roughly 3 times bo for HG AM2 for example. I have divided by bo for the MPD and the outputs match the mcmc. The mcmc calculation is sbt/bo because I saw that sbo = bo in the mcmc output. Perhaps I didn't run it out long enough to see a change? 

I have to head out now but will investigate further in the morning.

**Comment by jaclyncleary** [comment]
Am I correct that I need to "decide" whether I want to include a plot or table of SB0 values, and that if I do, that we need to re-run the mcmc's? (not a desirable option...)

**Comment by cgrandin** [comment]
To do that you would just need to re-run the mceval step for each model, so it wouldn't take too long.

**Comment by cgrandin** [comment]
I just ran out the mcmc to 50,000 and bo=sbo exactly for every sample. So we need to figure out asap how to fix this.

**Comment by jaclyncleary** [comment]
Sarah- Chris and I realized that the sbo and bo values captured in the mcmc file ARE the same because the bo comes from the slowMSY calc (Robyn's code) so they are meant to match. Chris is going to remove the bo output from the mcmc file so that this doesn't confuse us next year.

**Comment by Shawkshaw** [comment]
Should I rerun the mceval when this is updated?

**Comment by cgrandin** [comment]
Yes, because the output will be called sbo instead of bo. I'll let you know in a bit

**Comment by cgrandin** [comment]
Or you could just go through and manually change the column name "bo" in each iscam_mcmc.csv file to "sbo", whichever is easier. I think the latter..

**Comment by cgrandin** [comment]
I have modified iscam-pbs to output sbo in the mcmc, so I'll close this. I will still need to modify the csas-latex code to make use of the new column name "sbo".
