### ISSUE TITLE
decision tables: AM2

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#15]
column 2 header: P(SB_2018 < LRP of 0.30SB0)
(the LRP is new for herring so wanting to be clear that 0.30SB0 is the LRP)

column 3 header: Med(SB_2018/ 0.30SB0)
(pls check the equation matches. This is intended to show the magnitude of difference between SB_2018 and 0.30SB.  Ie, if the median ratio is 1.0 then SB_2018 ~= 0.30SB0, whereas if the median ratio is 2.5, then SB_2018 is 2.5x greater than 0.30SB0 (and so on).

column 4:  P(SB_2018 < 10,700 t)

column 5: Med(SB_2018/ 10,000 t)

cols 6:9 - great as is.

for AM1: same edit to header needed for col 3

**Comment by cgrandin** [comment]
Working on this...

**Comment by cgrandin** [comment]
Column 3: The calculation is correct but based on bo, not sbo so that is probably why it doesn't look right.

**Comment by jaclyncleary** [comment]
I think we can close this.

**Comment by cgrandin** [comment]
Yes, it's correct..
