### ISSUE TITLE
model diagnostics

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#16]
Chris, FYI:
Matt and I are going to meet tomorrow AM to review model diagnostics and determine if there's anything else we need. Off the top of my head, I'm recalling:

-age proportion bubble plots for each gear type (x3)
-a plot to show distribution of sbt in 2017, with 0.30SBo (LRP) so that we can "see" probability of being below LRP in 2017

**Comment by cgrandin** [comment]
Let me know where and when and I'll join if you like. I have code that does the bubble plots for knitr.
