### ISSUE TITLE
Sensitivity Analysis Maturity table

### ISSUE THREAD

**Issue by Shawkshaw** [cgrandin/csas-latex#17]
Can we create a table of maturity vectors used for the Maturity sensitivities?
Added Maturity-vectors.csv file to the data folder.

**Comment by cgrandin** [comment]
[Mat_Sel_table.pdf](https://github.com/cgrandin/csas-latex/files/1325109/Mat_Sel_table.pdf)

**Comment by cgrandin** [comment]
Done in coommit 2c8f5f694d50cf2253ef1f18b440cc42574afe37
