### ISSUE TITLE
age proportion bubble plots

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#18]
as discussed: age proportion bubble plots (model estimates) for each gear type (x3) x 5 stocks (AM2 only)

**Comment by cgrandin** [comment]
Numbers-at-age estimates will have to be MPD estimates - they are not output in the MCMC at this time.

**Comment by jaclyncleary** [comment]
works for me

**Comment by cgrandin** [comment]
Done in commit 239f9bdcf751d4399138e4da0c0febf03903dcab
