### ISSUE TITLE
plot distribution of sbt in 2017, with 0.30SBo (LRP) so that we can "see" probability of being below LRP in 2017

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#19]
a plot to show distribution of sbt in 2017 (histogram), with 0.30SBo (LRP) so that we can "see" probability of being below LRP in 2017

**Comment by grinnellm** [comment]
![currentssb](https://user-images.githubusercontent.com/25674027/30766753-1694e7c4-9fac-11e7-863e-bc213254965b.png)

**Comment by grinnellm** [comment]
Here's CC. Is this what you were thinking? Ie the vertical black lines show the median and 90% CI for SB_2017, and the red line is median 0.3SB_0. Or did you want the median and 90% CI for the 0.3SB_0. I made it this way, and then realized that you might want the later instead..

**Comment by jaclyncleary** [comment]
I think it's about interpretation.
When I look at this figure I see that with both AM1 and AM2, that SB_2017 is greater than 0.30SB_0 (median value) with greater than 95% probability. Does my interpretation make sense?

**Comment by grinnellm** [comment]
Your interpretation makes sense. I guess I'm wondering about the uncertainty on 0.3B_0 -- do we want to include that? For example, I could add red dashed lines for the 95% CI on 0.3B_0.

**Comment by grinnellm** [comment]
![currentssb](https://user-images.githubusercontent.com/25674027/30822283-0ec0c74c-a1dd-11e7-911d-6fc7340c8743.png)

**Comment by jaclyncleary** [comment]
I think why not. We can, and the different colours makes it clear. Thanks!

**Comment by grinnellm** [comment]
![currentssb](https://user-images.githubusercontent.com/25674027/30827924-b4bb57d0-a1f0-11e7-9d30-a23ee557234a.png)

**Comment by grinnellm** [comment]
Or I could do it like this, which seems a bit clearer to me, but I'm fine with either way.

**Comment by jaclyncleary** [comment]
I think this is less confusing than the straight lines. thanks.
