### ISSUE TITLE
plots for sensitivity analysis: natural mortality

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#20]
Chris- my take from our meeting last Friday is that you have the structure already in place from Arrowtooth to put multiple sensitivity cases on one plot. (pls correct me if I'm wrong)

**sensitivity case #1**: compare estimated time varying natural mortality (base) and constant estimated M

For **each stock** we want to plot:

(1) **model fit to survey data** (MPD estimates): 4 lines (constantM, timevaryingM, AM1, AM2)
(2) **SB ~ t**: 4 lines (constantM, timevaryingM, AM1, AM2)
(3) **recruitment deviations ~ t**: 4 lines (constantM, timevaryingM, AM1, AM2)
(4) **q ~ t (**MPD estimates): 4 lines (constantM, timevaryingM, AM1, AM2)
(5) **nage2 ~ t**: 4 lines (constantM, timevaryingM, AM1, AM2)
(6) **mortality ~ t**: 4 lines (constantM, timevaryingM, AM1, AM2)

And needing to see the MCMC diagnostics, so please add plots of: 
priors vs. posteriors
mcmc trace plots
pairs plots

We won't need to include them all in the Res Doc but we can't look at them without first including them...

**Comment by cgrandin** [comment]
Yes, it should be possible, but they might not be the prettiest with the little time we have left. I'd need the model output asap though. I don't see it on the private herring repo

**Comment by jaclyncleary** [comment]
they're here:
./github/Herring/2017mcmc/01_Natural_Mortality/Stock/AM1_constantM

etc

**Comment by Shawkshaw** [comment]
If you fetch and merge with me again they should all also be in the models_new folder (I updated this morning):
-AM1cM/AM2cM are constant M and 
-the base case AM1/AM2 are the timevaryingM

**Comment by cgrandin** [comment]
Thanks. I may have to restructure the directories to get the code to work though.

I've also noticed that in the private Herring repo, there are no mcmc folders inside the model folders.  So they have to be made manually and everything moved over each time or the code won't work.. Can I do this then push to that repo so it doesn't have to be done again?

Thanks Sarah, I did merge a couple of hours ago

**Comment by grinnellm** [comment]
The script ResearchDocumentV2.R has a function to move the *_mcmc.csv files to a subfolder "mcmc".
ArrangeOutput()

**Comment by cgrandin** [comment]
Great.. thanks Matt

**Comment by cgrandin** [comment]
On the biomass plots that I've just added, the CIs are plotted for all models. The shaded area represents the AM2 model's uncertainty.

**Comment by cgrandin** [comment]
`nage2` is the first column of N in the rep file right? I don't think there are any outputs for it in the mcmc.

**Comment by cgrandin** [comment]
q is just a single number, i.e. there is no q time series to plot

**Comment by grinnellm** [comment]
Correct me if I'm wrong..
I get nage2 from "iscam_rt_mcmc.csv" for the MCMC runs to calculate median and CIs, and I get nage2 from "iscam.rep" ($rt) for the MPDs.
And there are two q's: a single value for q1 from 1951 to 1987, and a single value for q2 from 1988 to 2017.

**Comment by Shawkshaw** [comment]
Correct, and this is what the time series of q looks like:
![4a_6a_q](https://user-images.githubusercontent.com/6414082/30940788-38bf76b8-a397-11e7-94f4-d6a44686d0ea.png)

**Comment by jaclyncleary** [comment]
plotting q~t: Matt's description is correct. so the plot is rather boring, e.g.,
![qplot](https://user-images.githubusercontent.com/2219398/30940661-a1a3333c-a396-11e7-8741-1d8a7c532d3a.png)

q-values can be taken from rep or iscam_mcmc.csv (what ever is easiest). When I added the plot to iscam-gui, I had to create a vector of length (1951:1987) for q1 and length (1988:2017) for q2 because for the q-vector in iscam.rep doesn't fill (it's all zeros)

nage2: 
yes- nage2 is the first column of N in the rep file right OR
you can use the nage2 from iscam_rt_mcmc.csv -- remember this matrix is missing nage2 for 1951 and 1952.   In V1 we had the mcmc outputs of nage2 saved as a .mcmc file so that is what you used for plotting last year (but we didn't add this yet).

**Comment by jaclyncleary** [comment]
in other words, the first column of N in the rep file is the same as rep$rt, but the model back-calculates the number of 2yr olds for 1951 and 1952 for the N matrix.

**Comment by cgrandin** [comment]
Thanks, that totally clarifies it!

**Comment by cgrandin** [comment]
Ok,  these are all done. The mcmc diagnostic plots really add to the length of time it takes to compile the document so I'm going to comment them out and we can uncomment the ones to be included later. I have attached pdf of them here so you can have a looksee

[herring-2017-mcmc-diags-sens-m.pdf](https://github.com/cgrandin/csas-latex/files/1342250/herring-2017-mcmc-diags-sens-m.pdf)

**Comment by jaclyncleary** [comment]
@cgrandin 
Geez HG-constantM have some ugly ski jumps in the pairs plots.
Also it looks like all the figure labels for stock-timevaryingM (e.g., Fig 6, 12, 18, 24, 30) need to be changed from constant natural mortality to "time-varying natural mortality".

**Comment by jaclyncleary** [comment]
Also, figure caption edit: The MCMC run had chain length 5 million, with a sample taken at every
**1,000th** iteration.
(final saved chain length is 5,000)

**Comment by cgrandin** [comment]
Ya those ones look like a rorschach test. I've just fixed those errors in commit 65fd23f92ac98c2328fad59bec90ec521914409e

**Comment by jaclyncleary** [comment]
I had to google that ;)

**Comment by Shawkshaw** [comment]
I updated the figures for this one in the 8_figures.rnw file in commit 39c405cfa01f136604fc3d0a20fc600daf5fd8d4 

The plots should be AM1_timevarying, AM1_constantM, AM2_timevaryingM and AM2_constantM 
I changed them all to the code below and hopefully I did not break them:
make.index.fit.plot(list(**hg.am1.constm,
                                     hg.am1.tvm,
                                     hg.am2.constm,
                                     hg.am2.tvm**),
                    start.yr = 1950,
                    end.yr = 2016,
                    ind = 1,
                    leg = "topright",
                    model.names = c("**AM1 Time-varying M","AM1 Constant M","AM2 Constant M","AM2 Time-varying M"**),

**Comment by cgrandin** [comment]
It's all working!

**Comment by Shawkshaw** [comment]
I notice we have fishing mortality plots for this sensitivity. 
Jaclyn do we also want the estimated Natural mortality?

**Comment by Shawkshaw** [comment]
I also can not figure out how to remove the index inputs bars and dashes from the index fits.  I think we want just dots for the input observed data. 
Is the file to change this doc/r/r-functions/figures-indices.r ?
Jaclyn, can you remember how you did this in the gui?
