### ISSUE TITLE
plots for sensitivity analysis: q

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#21]
sensitivity case #3: changing the sd for prior on _q_

**Comment by Shawkshaw** [comment]
Here we wanted to see plots for:
-prior and posterior distributions on q (AM1, AM1qa, AM1qb, and AM1qc)
-4 panel plots for each AM1qa, AM1qb, and AM1qc:
     -Sbt
     -Depletion
     -Mt
     -qt

Correct me if I am wrong Jaclyn

**Comment by jaclyncleary** [comment]
yes.
Chris- these are the plots we need for sensitivity case #3.

Note: 
sensitivity case 2 - no figs.
case 4- currently working on tables.

**Comment by cgrandin** [comment]
This is what I'm working on now, but I have to get the loading steps in place first.

**Comment by cgrandin** [comment]
Here's the q sensitivity priors/posts

[herring-2017-mcmc-sens-q.pdf](https://github.com/cgrandin/csas-latex/files/1342557/herring-2017-mcmc-sens-q.pdf)

**Comment by cgrandin** [comment]
I will add them into the doc tomorrow, I have to go now

**Comment by cgrandin** [comment]
Here are the q sensitivity 4-panel plots. I'll put the code in the doc next.

[herring-2017-4panel-sens-q.pdf](https://github.com/cgrandin/csas-latex/files/1345797/herring-2017-4panel-sens-q.pdf)
