### ISSUE TITLE
Plot: time series of effective harvest rate

### ISSUE THREAD

**Issue by grinnellm** [cgrandin/csas-latex#23]
I can't remember what we decided for this plot of SSB/(SSB+C) by year:
- SSB is the MPD, or
- SSB is the median, and 90% CI,
- other?

**Comment by jaclyncleary** [comment]
If possible, create the plot using median posterior values, dividing the envelope by Ct.
If MPD is more straightforward (given time constraints), this will certainly do.

**Comment by grinnellm** [comment]
Oops, it should be C/(SSB+C), right?
Here's the Median and 90% CI of SSB.

**Comment by grinnellm** [comment]
![harvestrate](https://user-images.githubusercontent.com/25674027/30830142-c7e21f36-a1f7-11e7-8353-afafdbeaad36.png)

**Comment by jaclyncleary** [comment]
yes

ut = C_t / ( C_t + SSB_t)

these plots are great. Can you add abline h=0.20 from 1983-2017? (these represent the years when intended 20%hr has been applied)
