### ISSUE TITLE
needing to verify that SB_2018 in Table 8 is the same as SB_2018 plotted in Figure 7

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#28]
Table 8 SB_2018 value for HG AM2 appears to be different than the value plotted in Fig 7 (d).

My hunch is that the value plotted in Fig 7 (d) is what is habitually used to reflect "projected spawning biomass assuming no fishing, SB_2018".  This is calculated from the TAC=0 rows in iscammcmc_proj_Gear1.csv, and uses "years" specified in the pfc file to calculate mean weight-age and average M.

My hunch is Table 8 SB_2018 values are median values of sbt1_2018 from iscam_sbt_mcmc.csv, which is calculated from the BH S/R assuming long-term average weight-age and M.

If my "hunches" are correct, can the SB_2018 values in Table 8 be changed to the values from iscammcmc_proj_Gear1.csv.  

@cgrandin I used something like this to calculate the median values and 90%iles:

p_sbt <- cbind(iscammcmc_proj_Gear1$TAC,iscammcmc_proj_Gear1$B2018)
p_sbt_median <- tapply(p_sbt[,2],p_sbt[,1],quantile,prob=0.5,na.rm=TRUE)
...
@grinnellm probably has a fancier R routine

**Comment by cgrandin** [comment]
Yes your hunch is correct.. I'll make the change :)

**Comment by cgrandin** [comment]
Done in commit 37c1fb3991f162090d8c068d6c879db9755b5de5
