### ISSUE TITLE
"arrowtooth" figures and tables needed for herring WP

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#3]
From the final Arrowtooth Res Doc, we would like to include:
Tables 1 and 2- NO b/c these are covered in Input Data Appendix (by MG)
Table 3- NO (survey inputs covered in Input Data Appendix (by MG)
Table 4- YES pls - Table label should state "initial values" (from par file)
Table 5, 6- Yes pls
Table 7- YES pls (single sex model, not female SSB), and ADD Depletion (as per Table 6 of 2014 Res Doc (./github/csas-latex/doc/CSAS 2014 Working paper.docx)
Table 8- YES pls- this needs to be age-2 recruits (not age-1)
Table 9- NO for now. I'm not sure how to add F's across gear types.
Table 10- YES but for herring U_t is calculated a bit differently- ask JC
Table 11- NO- b/c adding depletion to Table 7
Table 12, 13- leave out for now
Table 14- Decision tables- JC will add a separate "issue"

Figure 1- NO (MG already added BC stock map)
Fig 2- NO (already added as 5-panel fig)
Fig 3, 4- NO (we've included age-prop plots - by MG)
Fig 5- NO
Fig 6- NO for now
Fig 7, 8, 9, 10, 11- YES - for Fig 8 - make the prior a darker black lline (lwd=2) - it's not showing up when printed
Fig 12- NO (b/c appears in storyboard)
Fig 13-16- NO
Fig 17- YES
Fig 18- NO (b/c only including MSY ref pts in sensitivity section)- as a table
Fig 19, 20- NO
Fig 21- NO (b/c in storyboard)
Fig 22-42- No for now. Haven't decided yet on figs for sensitivity cases

**Comment by cgrandin** [comment]
Table 6 - not done. There are no msy refpoints so only the B0 ones would apply. I'll come back to it after doing the others.

**Comment by cgrandin** [comment]
I will also have to come back and fix the parameters estimated posteriors table (make.parameters.est.table()) once the models include B0

**Comment by cgrandin** [comment]
The reference points table was done in commit a1598de749b46682904356c1e8ce82bf2ba5970a

**Comment by cgrandin** [comment]
The parameters estimated posteriors table was fixed and B0 added in commit 21032e8fbd97cbe589f2512fe57c53fbe97e77d0
