### ISSUE TITLE
Appendix D and E

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#31]
Please add: 
Appendix D "Assessment of Minor Stocks"
Appendix E "Bridging Analysis" - this will be a PDF that we need to merge/ fix format for later... Chris suggests to make this the final Appendix to make page numbering easier.

**Comment by grinnellm** [comment]
Will do. Should be up momentarily.
Was that you writing about sigma=0.58 and tau=0.69? If so, don't forget to end the equations with a `$` -- you forgot two, which broke latex. Fixed:)

**Comment by Shawkshaw** [comment]
That was me Matt sorry I am very new to latex :)

**Comment by grinnellm** [comment]
No worries! I was just confused because I assumed that it was me who broke it. And I did, but not that part:)

**Comment by grinnellm** [comment]
Also, some latex tips in case they're useful:
- Don't put more than one sentence per line (easier to debug, will cause fewer merge conflicts).
- Check the log file `res-doc.log` to trouble shoot errors.
- If you're copy/pasting from MS word, do it in small chunks and beware symbols and funny characters.
- Compile the PDF often.
- Comment/uncomment lines, or entire sections (by commenting the lines in `res-doc.rnw`) to debug.
- Beware of symbols such as `#`, `&`, `$`, and `\` -- these are like functions in Latex.
- Try not to `push` to Github if your version doesn't compile.
- Use `%` to comment a line (not `#`)

**Comment by jaclyncleary** [comment]
Compile the PDF often.

What should we do about this given I can't compile on the mac?
Is it helpful if I send you an email stating "completed 1.1 Context.., please compile"?

**Comment by grinnellm** [comment]
I'm not sure. That's an option, but not great. It might be worth working with Chris to fix this mac issue?

**Comment by grinnellm** [comment]
It's broken again. I'll try to debug it tonight after the kids are in bed. I really think it'll be worth our time as a group for everyone to be able to compile this -- it'll be faster to debug one's own mistakes than someone else's.

**Comment by jaclyncleary** [comment]
Sounds like it. I'll ask Chris if he/you/I can try to get this working tomorrow AM with mac. In the meantime I will type elsewhere.

**Comment by grinnellm** [comment]
You might be able to type in the doc, and we/I can fix it tonight or in the am, while Chris tries to make it go on your mac. Unfortunately I can't send you a PDF right now because I can't make it:(

**Comment by jaclyncleary** [comment]
shoot.

**Comment by grinnellm** [comment]
Or maybe you can borrow a loaner laptop? I've gotten them from Gloria in the past, when traveling.

**Comment by grinnellm** [comment]
I noticed some math in the intro, which is suspect is not what you want. For example, see:
![image](https://user-images.githubusercontent.com/25674027/31026659-171e4604-a4fc-11e7-9277-6f9612c485d3.png)

**Comment by jaclyncleary** [comment]
thx, I'll make this fix
