### ISSUE TITLE
Update formatting for the Bridging Analysis appendix

### ISSUE THREAD

**Issue by grinnellm** [cgrandin/csas-latex#32]
I have added an appendix that brings in "BridgingAnalysis.pdf" (now should be in "csas-latex/doc"). The page numbers get added automatically, as are headers. We need to remove page numbers and headers from "BridgingAnalysis.pdf" -- you'l see when you compile it.

**Comment by jaclyncleary** [comment]
Do we want this title: APPENDIX E. BRIDGING ANALYSIS

**Comment by grinnellm** [comment]
I think I can make the title from Latex, and it'll be as you say above.

**Comment by jaclyncleary** [comment]
[Bridging Analysis DRAFT_forLaTex.pdf](https://github.com/cgrandin/csas-latex/files/1335287/Bridging.Analysis.DRAFT_forLaTex.pdf)


let me know if this works

**Comment by grinnellm** [comment]
That seems fine (i.e., good enough for a draft!).
