### ISSUE TITLE
Table for Maturity sensitivity resulting msy reference points

### ISSUE THREAD

**Issue by Shawkshaw** [cgrandin/csas-latex#33]
We will need a table with the Fmsy values estimated for the maturity schedule base case and the sensitivity case.  

Jaclyn, this is what we wanted to present for the results here correct?

**Comment by jaclyncleary** [comment]
@Shawkshaw Can you paste or email me the example?

**Comment by Shawkshaw** [comment]
[MSY reference points table.pdf](https://github.com/cgrandin/csas-latex/files/1335271/MSY.reference.points.table.pdf)
This is what I was thinking?

**Comment by jaclyncleary** [comment]
sounds good. can you put base case in the first column, and order stocks HG -> WCVI.
and for second column add descriptor, e.g., Sensitivity case: maturity set equal to selectivity

There has to be something wrong with the estimation of Fmsy for HG. It doesn't make sense that the Fmsy values increased in the sensitivity case. Unless it's the Ms... What do the M's do?

**Comment by Shawkshaw** [comment]
Added csv file to the data folder with sbo and sb2017 included as well. 
[Maturity sensitivity results table.pdf](https://github.com/cgrandin/csas-latex/files/1350602/Maturity.sensitivity.results.table.pdf)
Matt, if you have luck with the variance sensitivity results table and you have time could you build this table as well?

**Comment by cgrandin** [comment]
Matt have you started this? If not I can do it

**Comment by cgrandin** [comment]
I did it - commit d0769acafea1de413f16cc51bc9ab63227d3cd11

**Comment by grinnellm** [comment]
Hah - you are fast. Thanks Chris, I was working on something else and haven't checked in.
