### ISSUE TITLE
compiling PDF on Mac

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#34]
Chris, my inability to compile the pdf has become inefficient. Do you have time Wed AM to try to troubleshoot this with Matt and I?

**Comment by cgrandin** [comment]
Sure, let me know when..

**Comment by grinnellm** [comment]
I'm available anytime.

**Comment by cgrandin** [comment]
Me too, I'll just wait to hear from Jaclyn

**Comment by jaclyncleary** [comment]
How about Chris's office, 945am

**Comment by cgrandin** [comment]
My roomie is here today, can I come over there?

**Comment by jaclyncleary** [comment]
yes, I'm in A206 (upper floor annex)

**Comment by cgrandin** [comment]
Ok, I'm heading there now.
