### ISSUE TITLE
Error compiling 

### ISSUE THREAD

**Issue by Shawkshaw** [cgrandin/csas-latex#36]
I am unable to compile this morning and I am receiving the following error:
! LaTeX Error: File `pdfpages.sty' not found.
 ==> Fatal error occurred, no output PDF file produced!

Was the \usepackage{pdfpages} just added to the res-doc.rnw or have I lost the package somewhere?

**Comment by grinnellm** [comment]
I added it last night -- it allows us to bring in the Bridging Analysis appendix. You'll have to get it (usually miktex installs missing packages on the fly, but I guess not for you in this case).

**Comment by cgrandin** [comment]
If you just google it, you'll find the file. Put it in the doc directory. FYI you'll also need eso-pic.sty

**Comment by cgrandin** [comment]
I think the Miktex servers are down again as I had the same problem

**Comment by grinnellm** [comment]
Ah, ok. Sorry I forgot to mention where to get the package..

**Comment by Shawkshaw** [comment]
Thanks!   I had to add the following to the doc directory:
cmap.sty
eso-pic.sty
pdfpages.sty
pppdftex.def
