### ISSUE TITLE
Include citations from the Bridging Analysis in all.bib

### ISSUE THREAD

**Issue by grinnellm** [cgrandin/csas-latex#37]
Need to get the citations from the Bridging Analysis into bibtex. These will be used in the rest of the document too.

**Comment by grinnellm** [comment]
Done. Now I'll work at putting them into our document.
For @jaclyncleary and @Shawkshaw: if you want another citation
- open the file "all.bib" with your favorite text editor:)
- `search` to make sure the citation you want isn't already there..
- go to the end of the file and copy/paste an existing citation
- update the contents, and make sure the first line `@article{xyz,` has a unique identifier (i.e., do a search for the `xyz` part)
- note that authors are separated by `and`, no commas

You can now cite the paper by using e.g., `\citet{xyz}`. For example:
- There are many herring in BC \citep{fu2004}, which has also been noticed by \citet{forrest2015}.

produces:
- There are many herring in BC (Fu et al., 2004), which has also been noticed by Forrest et al. (2015).

http://merkel.texture.rocks/Latex/natbib.php

And for cross-referencing, look here:
https://en.wikibooks.org/wiki/LaTeX/Labels_and_Cross-referencing

**Comment by jaclyncleary** [comment]
@grinnellm 

How do I type the subsubsection reference:

"... are presented in Section **2.4.4 Maturity at age** of the Sensitivity Analyses."

**Comment by grinnellm** [comment]
Go the the subsubsection that you want to reference, and make a new label that makes sense, say `\label{secMatAge}`. Put it on the same line as the subsubsection, at the end of the line. Then you can refer to it elsewhere by, say "as described in \ref{secMatAge}."
