### ISSUE TITLE
Table for Variance parameter sensitivity analysis

### ISSUE THREAD

**Issue by Shawkshaw** [cgrandin/csas-latex#38]
[Obs_proc_error_sensitivities.pdf](https://github.com/cgrandin/csas-latex/files/1338358/Obs_proc_error_sensitivities.pdf)

Do we need to show all stocks? 
There are 2 table (AM1/AM2) for each stock but they all show the same thing that regardless of initial rho and kappa values the estimated values for all leading parameters are the same if estimation is on for both rho and kappa.

**Comment by jaclyncleary** [comment]
let's show just one stock and please make a comment in the text to indicate all stocks show the same thing.... For consistency with Bridging Analysis, show SoG.

**Comment by Shawkshaw** [comment]
I added the data for the rho and kappa initial values and estimated values for this table into the data folder.

**Comment by grinnellm** [comment]
Do you want this as a table in the main doc? Same layout as the attached PDF?

**Comment by Shawkshaw** [comment]
That would be great!  We only need SOG AM1 and AM2 though. csv file is in the data folder:)

**Comment by grinnellm** [comment]
I can work on this, but I'm hesitant to do this (something I haven't done before) while the document is broken -- I won't be able to see if it's actually 'working'. Might make it harder for Chris to figure out what the current issue is.

**Comment by Shawkshaw** [comment]
I was feeling the same way about it LOL I didn't want to break anything!

**Comment by grinnellm** [comment]
Oh now I see -- that's why you assigned it to me?! :)

**Comment by cgrandin** [comment]
It should be working now, I had to fix more cite commands and it build fine here

**Comment by grinnellm** [comment]
This CSV has 6 sensitivity cases (not 5 like the PDF; attached above): 1 to 5, and 'Base'. Which do you want: all 6 (including 'Base') or just the 5 numbers?

**Comment by Shawkshaw** [comment]
The pdf does not have the base run in it... Probably a good idea to include the base as well if it  all fits.

**Comment by grinnellm** [comment]
I've updated the doc to try to bring this table in, but it's not working yet. I think I'm close. Maybe @cgrandin can take a look? This was on commit a76a889f95eed51a74bdb03927e040e0bcd85f96. The error I get in the PDF, where the table should be is:
`## Error in ‘colnames<-‘(‘*tmp*‘, value = c(latex.bold("Stock"), latex.bold("Model"), : attempt to set ’colnames’ on an object with less than two dimensions`

**Comment by cgrandin** [comment]
I'll have a look once I do the sbo changes..

**Comment by cgrandin** [comment]
What are the columns? I just see Base_Initial, 1_Initial, 2_Initial, etc

**Comment by cgrandin** [comment]
I'll duplicate the tables from the pdf, but I don't know what to write for the captions.

**Comment by grinnellm** [comment]
Thanks Chris. I guess that was my error? I'm not sure how to specify column names.

**Comment by cgrandin** [comment]
Yeah, the whole table needs to be constructed from scratch to get the multicolumns, etc. Also I notice that only SOG data are in the csv file. Should all stocks be in there?

**Comment by grinnellm** [comment]
No, we only need SoG.

**Comment by cgrandin** [comment]
Done in commit ebde034ab98c6b6417035eb78f938a962ecd41f3
