### ISSUE TITLE
Citations for Introduction

### ISSUE THREAD

**Issue by grinnellm** [cgrandin/csas-latex#39]
Is it safe to assume the citations that are still hard-coded into the introduction need to be worked into all.bib? I've started on this already..

**Comment by jaclyncleary** [comment]
yes. the only one I've changed is Martell 2012

**Comment by jaclyncleary** [comment]
there are also two more weblink citations to format - last paragraph of section MANAGEMENT OF MAJOR HERRING STOCKS

**Comment by jaclyncleary** [comment]
values missing in this ref:
Kronlund, A.R., Forrest, R.E., Cleary, J.S., and Grinnell, M.H. 2017. The selection and role of limit reference points for Pacific Herring (Clupea pallasii) in British Columbia, Canada. DFO Can. Sci. Advis. Sec. Res. Doc. 2017/**xxx**. viii + **xx** p.

**Comment by grinnellm** [comment]
Done:) 
PS I wrote the `\mli{}` function to make variable names in math mode, so it has to be inside `$ $`. It makes nicer kerning just for multi-letter variable names, such as `SB`. This is because LaTeX seems to like one-letter variable names best, and doesn't look as nice if you have an actual word for a variable name. If you just want italics/emphasis in a paragraph setting, you can use `\emph{xyz}`

**Comment by grinnellm** [comment]
Now I'm working on citations in the 3_modelling.rnw.
