### ISSUE TITLE
deleting knits-cache

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#41]
@cgrandin 
I found two options for rmdir
rm -R knitr-cache
rm -iR knitr-cache

The latter gives a prompt to ask 'are you sure'. Is the object to delete everything in the knitr-cache, including the folder? Including __packages?  If yes, then seems the first option is best. Just wanting to check given it's final.

**Comment by cgrandin** [comment]
Yes, you should delete the whole folder and everything in it if you want all figures/tables remade.

You can also just delete select figure/table objects from there if you want, then only those ones would be remade. I often do that to make it faster when working on one figure/table.
