### ISSUE TITLE
new mcevals in Herring/2017mcmc/models

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#44]
Sarah (thanks!!!) has rerun the mcevals for all mcmc. The new files are in Herring/2017mcmc/models directory -- **sbo** is now in the iscam_mcmc.csv file.

**Comment by jaclyncleary** [comment]
@cgrandin - please post when you've adjusted plots and tables using sbo
@grinnellm - please post when you've adjusted plots for sbt_2017/sbo

Thanks

**Comment by Shawkshaw** [comment]
The push to the herring repo failed last night and is moving slowly this morning... I will update when the new mcmc are updated (Currently at 34%)

**Comment by cgrandin** [comment]
That explains why I have no 2017mcmc directory now.. Thanks Sarah, I'll merge as soon as you're done

**Comment by jaclyncleary** [comment]
I too didn't realize this. Sarah, pls msg when it's done.

**Comment by Shawkshaw** [comment]
Sorry everyone, it is loading very slowly only at 38% now...

**Comment by Shawkshaw** [comment]
I had to load the files individually and I am almost finished:)  If you get a chance to fetch/merge now and then again when all are loaded it might go faster so you are not loading everything at once...

**Comment by Shawkshaw** [comment]
All new mcmc runs are up in the Herring repo!
