### ISSUE TITLE
Are we doing retrospectives?

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/csas-latex#45]
I thought you had planned to run them but I don't see them in the Herring repository.

**Comment by Shawkshaw** [comment]
Yes I have run them but they are in the 2017mcmc file that is being reloaded... Sorry should be back on there soon

**Comment by cgrandin** [comment]
Great - thanks!

**Comment by Shawkshaw** [comment]
Retrospective runs are all up in the Herring/2017mcmc folder again

**Comment by cgrandin** [comment]
Thanks, I have them now. Whew, a whole day to upload everything. I bet you're relieved it's over!

**Comment by Shawkshaw** [comment]
Yes!  I was nervous I wasn't going to get them back on there....

**Comment by jaclyncleary** [comment]
do we have figures for this section?

**Comment by cgrandin** [comment]
Not yet, I still have to get them loaded in and then make the figures. That is my plan for today.

**Comment by cgrandin** [comment]
I've done the retrospective biomass plots and will do the recruitment plots next. I think that's all that time will allow for at this point.

**Comment by grinnellm** [comment]
What's the proper folder structure for these retrospective models? Looks like we need to update it to this:
Error in create.rdata.file.retro(model.dir = file.path(retro.dir, stock.dir[i],  : 
Error - the directory ../../retrospectives/HG/01/HG/AM1 does not exist. Fix the problem and try again.

**Comment by cgrandin** [comment]
If you merge with Sarah, she kindly fixed it up so there's no need to change it. Just put a retrospectives folder containing them in the same folder that the models folder is in (csas-latex)

**Comment by grinnellm** [comment]
Thank you Sarah - I was not looking forward to dealing with all the mistakes I'd make while moving and renaming folders!
