### ISSUE TITLE
Natural Mortality sensitivity plots

### ISSUE THREAD

**Issue by Shawkshaw** [cgrandin/csas-latex#46]
Chris, 
When you get a chance could you please change the Fishing Mortality plots to the estimated Natural Mortality plots for the Natural Mortality sensitivities?
And can you confirm what the CIs for the inputs are based on in the index fits plots?

Thank you!

**Comment by cgrandin** [comment]
Yes.. The bars are the CV which are 1/weight. The weight comes from the dat file but I see they are all set to 1 for herring. I was actually just in the process of removing these!

I'll get to the mortality plots after that.

**Comment by Shawkshaw** [comment]
Awesome thank you!

**Comment by cgrandin** [comment]
Changed to natural mortality plots in commit 5e3c650de5ad02f5d964c8fb08cbbaa6114071a1
