### ISSUE TITLE
Legend wrong for all the natural mortality sensitivities plots

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/csas-latex#47]
Arrg - Sorry! The TVM and constantM legend items are all opposite. I'm fixing it but wanted to get this up in case you are working on it. I hope it doesn't mean rewriting whole sections

**Comment by Shawkshaw** [comment]
That is okay!  I see where the problem is, I can update these if you like?

**Comment by cgrandin** [comment]
I've already started, so don't worry about it..

**Comment by cgrandin** [comment]
Ok, it's fixed in commit 5e3c650de5ad02f5d964c8fb08cbbaa6114071a1
