### ISSUE TITLE
ArrangeOutputs() breaking on new model outputs

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/csas-latex#48]
Hey Matt, there are no mcmc outputs in the AM1Mat and AM2Mat directories so it stops on each of them. It would be good if it just continued

**Comment by cgrandin** [comment]
For now this works if you just source it a bunch of times (10), so not really a high priority.

**Comment by grinnellm** [comment]
Should be fixed now. I guess my new 'feature' was a bust..
