### ISSUE TITLE
Old files in '2017mcmc' -- can they be deleted?

### ISSUE THREAD

**Issue by grinnellm** [cgrandin/csas-latex#49]
It seems the old (i.e., previous version with bo, not sbo) "*mcmc.csv" files are present in the folder, in the /mcmc subfolders. This is getting in the way of my script -- it thinks that these are the correct files, and doesn't move the new files to their correct place. That may not make sense. Can I delete all the /mcmc subdirectories from 2017mcmc? And the .tex and .png files too? That'll make it smaller too.

**Comment by Shawkshaw** [comment]
Yes you can delete these... I thought I had deleted all the old mcmc.csv files in the repo so these might just be on your computer now.  https://github.com/Shawkshaw/Herring/tree/master/2017mcmc/models

As for the .tex and .png files will these be over written when compiling again? or is it better to remove them?

**Comment by Shawkshaw** [comment]
Oh looks like I did not get all the mcmc files... I will remove these from the repo now:)

**Comment by Shawkshaw** [comment]
All the mcmc files should really be removed now if you fetch and merge again.  Sorry about this:)

**Comment by grinnellm** [comment]
Thanks Sarah! 
No need to delete the .tex and .png files as they do get overwritten. But it would make it a tad bit faster, and prevent someone from looking at outdated results. Maybe for next time?
