### ISSUE TITLE
Need to fix how references are handled on mac

### ISSUE THREAD

**Issue by grinnellm** [cgrandin/csas-latex#5]
I can't generate the document on my mac at home; having the same issues that Jaclyn and I were having on her mac. Not sure why this is yet: a mac issue, or something else?

**Comment by cgrandin** [comment]
Any more info on this? I don't have a mac so I can't test it.

**Comment by grinnellm** [comment]
I sent you an email -- I hoping that we can narrow it down if someone else can compile the PDF on a windows machine.

**Comment by grinnellm** [comment]
Seems like this is just a mac issue; low (or none?) priority for now.

**Comment by cgrandin** [comment]
It would be good if everyone could build the doc on the fly - I want to help but I don't have a mac to test on

**Comment by grinnellm** [comment]
I wonder the mac doesn't grab citations because of the path to "all.bib"?

**Comment by grinnellm** [comment]
@jaclyncleary Did that work to put quotes around the call to `all.bib` in `bibliography`?

**Comment by grinnellm** [comment]
I had to change it back (remove the quotes) to make it work on my machine. If the quotes worked for you, I'll get a solution:)

Also, I changed the Martell citation back to `martell2011` -- the identifier should stay the same because I suspect it's been used in other documents. However, we can update the year to 2012, so I left that:)

**Comment by jaclyncleary** [comment]
@grinnellm 
I don't think so but I will check again. Pls remind me again where to do this.

**Comment by grinnellm** [comment]
I think you updated the line in "6_acknowledgements.rnw" from `\bibliography{../../all}` to `\bibliography{'../../all'}` --  is that right?

**Comment by jaclyncleary** [comment]
@grinnellm 
nothing changes, still not working.
I'll see if Sean Anderson has any suggestions.

**Comment by jaclyncleary** [comment]
I have references!! I have no idea what changed (faeries, or magic-matt) but they're working!

**Comment by grinnellm** [comment]
Nice! Maybe because I moved the lines to load "res-doc.bst" and "all.bib" to the main "res-doc.rnw" file? That, or the whims of bibliography faeries.
