### ISSUE TITLE
labels in 7_tables...

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#51]
@cgrandin - there are still two Tables one for each of AM1 and AM2 that use labels that look like this:

xlabel = "tab:wcvi-spawn-biomass"

**Comment by cgrandin** [comment]
Ok, I thought you were talking about the knitr code chunk name. You can change the am1 one to wcvi-spawn-biomass-am1 or whatever you'd like.

**Comment by cgrandin** [comment]
I've done loads of cut/paste so there might be a few little things like this. I tried hard to catch them all though.

**Comment by cgrandin** [comment]
I tend to name them the same as the code chunk name so you know what files correspond to them as well.
