### ISSUE TITLE
Table with projected PropAge3 and PropAge4to10 for 2018

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#54]
Is it possible to request a table summarizing the PropAge3 and PropAge4to10 for 2018?

These proportions are outputted in iscammcmc_proj_Gear1.csv and are the same for each TAC value.

Proportions to 2 decimal places only.

**These could be added to this table: hg.ref.points.table, prd.ref.points.table**
or if it's easier to make a separate table then I only need AM2 (results are near-identical between AM2 and AM1).

**Comment by cgrandin** [comment]
I'll do this..

I've finished all my other tasks so if you can think of anything else you need for tomorrow that would be great as I start earlier.

**Comment by jaclyncleary** [comment]
@cgrandin I'm going to print the doc and look to see if there's anything else that I need. I'll update as an issue.

**Comment by cgrandin** [comment]
This is taking a bit longer than expected due to me having to run build() several times this morning. It's coming along fine, just a slow process.

**Comment by cgrandin** [comment]
Finally! This turned out to be super tricky but it's done in commit 66b4244f7a6807391a539bdd75c23ddd98557b08

You'll need to delete the rdata files and build() again first

**Comment by cgrandin** [comment]
Hold off build() until I fix issue #64 - it will be required for that fix as well
