### ISSUE TITLE
Add AM1 Tables for leading parameter estimates.

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#55]
I'm seeing leading parameter estimates - specifically q-values, reported for AM2 but not for AM1.
I think the easiest is if you could please add hg.parameter.est.table, prd.parameter.est.table, etc, for AM1 outputs.

I know it's a crazy amount of tables, but adding 5 more is probably easier than making a q-specific table.

**Comment by cgrandin** [comment]
No problem.. I will get to it

**Comment by cgrandin** [comment]
Done in commit d5e56a2b0db0a878eca8b885e8b5a904e416d8e0.
