### ISSUE TITLE
Natural mort sensitivity M estimate plots 

### ISSUE THREAD

**Issue by Shawkshaw** [cgrandin/csas-latex#56]
These figures (76-80) are showing up as:
 ## Error in plot.window(xlim = xlim, ylim = ylim, xlab = "", ylab = ""): need
finite 'xlim' values

Is this just me?

**Comment by cgrandin** [comment]
Mine is broken elsewhere (in text) so I'll get back to you

**Comment by grinnellm** [comment]
Those figures are working for me. 
@cgrandin you might have to source `ResearchDocumentV2.R` -- I added some new R variables last night. Not sure if that's breaking for you now, but you will have to..

**Comment by cgrandin** [comment]
Ok thanks. and yes those figures work for me also.

**Comment by jaclyncleary** [comment]
me too

**Comment by Shawkshaw** [comment]
hmm well I will try to figure this out later:)
