### ISSUE TITLE
I commented out some plots for the sensitivity analysis

### ISSUE THREAD

**Issue by Shawkshaw** [cgrandin/csas-latex#58]
There are some plots that we decided would be unnecessary and these were commented out.  Don't worry if there are less plots now...

**Comment by Shawkshaw** [comment]
I also removed the 0.3Bo from the sbt plots in the natural mortality sensitivity plots because there are multiple models plotted and we do not now which one this belongs to...

**Comment by cgrandin** [comment]
It was the base AM2 model but what you did is probably easier than writing that in all the captions. It's also in the retro biomass plots and is the base value without any years removed.
