### ISSUE TITLE
Figures and tables in appendices - not working

### ISSUE THREAD

**Issue by grinnellm** [cgrandin/csas-latex#6]
The document can now bring in two appendices: app/A_biology.rnw and app/B_equations.rnw (these were causing errors). I think the errors were because these appendices were trying to load files for tables and equations, but those files aren't being generated yet (hopefully the required ones will be generated when we have the output for multiple stocks).
In A_biology, I commented out the R code to make 3 plots (fig:vonb, fig:lw, and fig:matage) -- Jaclyn should know which, if any, of these are required.
In B_equations, I commented out the code to make 4 tables (tab:variables, tab:steady-state-model, and tab:catch-age-model).

**Comment by cgrandin** [comment]
In the Arrowtooth assessment, the figures in A_biology.rnw came from data output by the iscam-gui biology tab (the three models have to run from there) and then stored as a binary rdata file called bio.rdata. This was loaded in and gave the variables used in the figure function calls.

**Comment by cgrandin** [comment]
The model equation tables now work (d72c22a7d04280db33bc69606faf24f275414cee).
The issue was that the base model variable 'b' didn't exist so I used hg.b instead. So the table will used the values from the Haida Gwaii model.

**Comment by cgrandin** [comment]
can we close this @jaclyncleary ?
