### ISSUE TITLE
Trying to uncomment mcmc diagnostic plots for HG M sensitivity runs

### ISSUE THREAD

**Issue by Shawkshaw** [cgrandin/csas-latex#62]
I have been trying to include the mcmc diagnostic plots ( priors.posts.plot, traces.plot and pairs.plot) for the natural mortality sensitivity (constant vs timevarying M) for HG only without success.  

I can see the code for these in the 8_figures.rnw around line 2264 but when I uncomment them I get an error when compiling and they do not show up... What am I missing??

**Comment by grinnellm** [comment]
Any update on this? I'm going to take a peek now..

**Comment by grinnellm** [comment]
This seems to work for me. I uncommented lines 2266 to 2307 in 8_figures.rnw, and I get 3 new figures. I'll email the PDF to you now, in case you need it tonight. I'll push my version, maybe there's something there that'll help yours work. If not, comment those lines.

**Comment by grinnellm** [comment]
What's your error message?

**Comment by Shawkshaw** [comment]
Thanks Matt, As long as it is working for you I will commit the changes so the diagnostic plots show up:) I will figure out my error later.

**Comment by grinnellm** [comment]
Nope, I fetched and merged with you, and now it's broken: 
`Line 405: Error in parse_block(g[-1], g[-1], params.src)`
I'll work on figuring this out.

**Comment by grinnellm** [comment]
I think that error might be occuring here: Line 405 in "8_figures.rnw"
`make.traces.plot(wcvi.b, axis.lab.freq = 200)`

**Comment by Shawkshaw** [comment]
It may be that the labels for am1 and am2 are the same... I changed the labels for am1 and pushed it again if you want to try that

**Comment by grinnellm** [comment]
I'm doing the same thing now -- there are a lot of duplicate labels.

**Comment by Shawkshaw** [comment]
okay maybe I missed some I only changed the am1 ones

**Comment by grinnellm** [comment]
Well, now I have a new error, seems to be in `make.natural.mort.mcmc.plot()` ugh

**Comment by cgrandin** [comment]
I thought I caught them all but clearly not.. I'm in the middle of the other issue so I can't help at the moment but when I'm done I'll merge and take a look.

It won't be the figure code, but something else before that.

**Comment by grinnellm** [comment]
I updated the R-code chunk names (that seems to have been causing some issues), and pushed. Don't merge unless you want a broken version.

**Comment by Shawkshaw** [comment]
I think it is the am1 versions I added

**Comment by grinnellm** [comment]
Which plots did you add/write?

**Comment by Shawkshaw** [comment]
I copied the am2 versions but clearly I missed changing something...

make.priors.posts.plot(hg.am1.constm, priors.only = FALSE)
make.traces.plot(hg.am1.constm, axis.lab.freq = 200)
make.pairs.plot(hg.am1.constm)
make.priors.posts.plot(hg.am1.tvm, priors.only = FALSE)
make.traces.plot(hg.am1.tvm, axis.lab.freq = 200)
make.pairs.plot(hg.am1.tvm)

**Comment by grinnellm** [comment]
Ok, thanks Sarah. I'm going to work on something else for Jaclyn right now, but I'll look at these in a bit. My suggestion (if you want to work at them yourself now) is to comment them all out, and see if it runs. If so, turn them on one-by-one to see exactly where it's broken.

**Comment by Shawkshaw** [comment]
Sounds good, I will see if I can fix it

**Comment by cgrandin** [comment]
It looks like you fixed it, mine compiles fine at 6a78f81351f6442fc2d38b700447e93a5ef9106d

**Comment by Shawkshaw** [comment]
I did not fix it...I just re commented the figures so I could work on the text... Still not working for me

**Comment by cgrandin** [comment]
Ok, I'm going to take a look now

**Comment by cgrandin** [comment]
I'll add them. So you just want HG models AM1 and AM2 priors, traces, and pairs added?

**Comment by Shawkshaw** [comment]
Yes please for the constant M only as the time-varying M should already be shown in the base case plots.

**Comment by cgrandin** [comment]
Done in commit 2c0dfc16d66e27e309d19ab4d8eb735c8008d60b
