### ISSUE TITLE
Errors in Probabilistic decision tables

### ISSUE THREAD

**Issue by grinnellm** [cgrandin/csas-latex#64]
There are two errors in the decision tables.

First, three of the fixed-cutoff values are wrong:
- The fixed-cutoff for PRD should be 12100 t (AM2 and AM1).
- The fixed-cutoff for CC should be 17600 t (AM2 and AM1).
- The fixed-cutoff for SoG should be 21200 t (AM2 and AM1).

I use this variable in my script (multiply by 1000):
`fixedCutoffs <- list( HG=10.7, PRD=12.1, CC=17.6, SoG=21.2, WCVI=18.8 )`

Second, two columns have the wrong names, and seem to have the wrong values/contents. This affects decision tables for PRD, CC, SoG, and WCVI (AM2 and AM1):
- The 4th column `P(U_2018 < [fixed.value])` should be `P(SB_2018 < [fixed.value])` as it is HG (which is correct). The column header needs to be updated to be SB not U, and the contents appear to be wrong.
- The 5th column seems to be wrong, since they're calculated using column 4.

**Comment by cgrandin** [comment]
No problem, this labels are easy but here is the code I have for SB_2018 < value:
`proj <- model$mcmc$proj`
`tac <- sort(unique(proj$TAC))`
`for(t in 1:length(tac)){`
`  d <- proj[proj$TAC == tac[t],]`
`  n.row <- nrow(d)`
`  val <- length(which(d[,"B2018"] < 10700)) / n.row`
`}`

It looks right to me, am I missing something?

**Comment by grinnellm** [comment]
Hmm, not sure. Jaclyn thought that HG and WCVI tables for AM2 and AM1 looked OK, but that columns 4 and 5 for the other stocks (both models) were wrong.

**Comment by grinnellm** [comment]
For example, look at SoG AM2. The stock is currently really high, so the probability that the biomass in 2018 will be less than 21.2 (or 17.6) shouldn't be 1.0 when the TAC is zero. Maybe I'm mis-interpreting the table?

**Comment by cgrandin** [comment]
D'oh, I wasn't multiplying the SB by 1000 first. Easy fix..

**Comment by grinnellm** [comment]
Small thing, but the second column seems to be missing a closing bracket, and either a space or an equals sign between `LRP` and `0.30SB_0`.
What ever is easy, or ignore it. The third column doesn't have `LRP`.

**Comment by cgrandin** [comment]
This is done in commit 716825935b19116ab7e140e16cba628e19c49f1e. 

Thanks for catching it Matt!

**Comment by grinnellm** [comment]
It was all Jaclyn.
