### ISSUE TITLE
browser()

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#66]
I get a browser() when I run library(knitr); knit(‘./res-doc.rnw’) [after build() and then fresh.sh]

function(x){
           browser()
           draw.envelope(yrs[[x]],
                         m.quants[[x]],
                         xlab = "",
                         ylab = "",
                         col = x,
                         las = 1,
                         xlim = xlim,
                         ylim = ylim,
                         opacity = opacity,
                         first = ifelse(x == 1, TRUE, FALSE),
                         …)}

which appears in FN (make.natural.mort.mcmc.plot())

I can type Q in the browser() and then it keeps going and I can continue to compile PDF from RStudio.

**Comment by cgrandin** [comment]
Sigh.. I left another one in there. I will delete it

**Comment by cgrandin** [comment]
8030e13e3397fa61017921c854bffd9e477a2c59
