### ISSUE TITLE
one more table (sorry...) [for q-sensitivities]

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#68]
@cgrandin 
I'm sorry to have to ask...

Can you please add a table that is the same format Table 2 (tab:q-parameters) with 

8 columns:
SAR
Model
Survey
Bounds
Prior (mean, SD)
q1 (MPD is fine)
q2 (MPD is fine)
SB_2017
SB_0
Depletion= SB_2017/ SB_0

and 40 (8 x 5 stocks) rows:
HG   AM1   Surface (q1)   None  Normal(0.566, 0.274) ...
HG   AM1   Surface (q2)  None   Normal(0.566, 0.274) ...
HG   AM1   Surface (q1)   None  Normal(0.566, 0.5) ...
HG   AM1   Surface (q2)  None   Normal(0.566, 0.5) ...
HG   AM1   Surface (q1)   None  Normal(0.566, 2.0) ...
HG   AM1   Surface (q2)  None   Normal(0.566, 2.0) ...
HG   AM1   Surface (q1)   None  Normal(0.566, 3.0) ...
HG   AM1   Surface (q2)  None   Normal(0.566, 3.0) ...

PRD   AM1   Surface (q1)   None  Normal(0.566, 0.274) ...
...
etc
...
WCVI   AM1   Surface (q2)  None   Normal(0.566, 3.0) ...

**Comment by cgrandin** [comment]
So this table will replace table 2 right?

**Comment by jaclyncleary** [comment]
well it can.
we need AM2 for all stocks as currently appears in Table 2.

Then add to this AM1 (only) for all 5 stocks:
HG AM1 Surface (q1) None Normal(0.566, 0.5) ...
HG AM1 Surface (q2) None Normal(0.566, 0.5) ...
HG AM1 Surface (q1) None Normal(0.566, 2.0) ...
HG AM1 Surface (q2) None Normal(0.566, 2.0) ...
HG AM1 Surface (q1) None Normal(0.566, 3.0) ...
HG AM1 Surface (q2) None Normal(0.566, 3.0) ...


Where the new column info comes from the q-sensitivity rep files.

**Comment by cgrandin** [comment]
Ok it's done in d785f965f686735f576a5f6ca3c98d8ab2b4bc71. 

The new table is last and table 2 has been modified.
I'll leave this open until you have a look

**Comment by jaclyncleary** [comment]
fetching now

**Comment by jaclyncleary** [comment]
Both Table 2 and Table 48 are perfect.
