### ISSUE TITLE
\subsubsection{Biomass and stock status} - reference newest table

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#76]
@grinnellm 
Once @cgrandin has completed Table with q-values, please add table citation to \subsubsection{Biomass and stock status

search: %MG5

**Comment by grinnellm** [comment]
The 'new' table (2) has medians of the MCMC posteriors for q's, not MPD as you mention in the text. MPDs are in the 'old' tables (one for each stock). Which would you prefer?

**Comment by jaclyncleary** [comment]
change the text to match the latest tables.
