### ISSUE TITLE
problem with 7_Tables

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#78]
I added some wording to the title for tab:variance-results-AM2 and tab:variance-results-AM1 and now I get the following text in place of the Table in the PDF:

 Error in (function (classes, fdef, mtable) :  unable to find an inherited method
for function ’select’ for signature "tbl_df"

I'm not sure what I broke... :(

This table is cited in \subsubsection{Variance parameters}, search %MG5

**Comment by cgrandin** [comment]
It's working fine for me on 915b6857b286d56c554af4e17ad8786dc5a52d09

**Comment by grinnellm** [comment]
Works for me too.
