### ISSUE TITLE
question about Figure 83

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#80]
anyone having 'git-issues withdrawal' yet? 

I have a question from Paul Starr. **"I note that Figure 83 (Haida Gwaii AM1 analysis) shows a very similar distribution as the previous five figures, but it is no longer centred around 0 and there is a prior plotted.  Why are there no MPD estimates plotted for these two parameters?"**

I'd like some help in the interpretation.

AM1 has q1 and q2 parameterized with informative priors: Normal prior with log mean prior 0.566 and sd prior 0.274.

Fig 83 is AM1, constant M, HG

I notice that we don't have a version of Fig 83 for AM1, estimate time varying M (i.e. the base)- see request in next issue.

1) I expect to see prior plotted for ln(q2) but unsure why we don't see a similar fig for ln(q1)
2) yes, adding MPDs to these figs and to ln(M) would be helpful.

**Comment by Shawkshaw** [comment]
I had plotted these in the gui for CC and SOG.  
-CC shows a similar trend for AM1 constant M as HG.  It looks like the prior distribution is just outside the scale as you can see the end of the tail.  
[01_NaturalMortality_mcmc diagnostic plots.pdf](https://github.com/cgrandin/csas-latex/files/1373008/01_NaturalMortality_mcmc.diagnostic.plots.pdf)

**Comment by cgrandin** [comment]
Most likely a bug in my code, with all the stuff we did they can slip by. Leave this open and I'll fix it as soon as I can, probably Thursday.

**Comment by cgrandin** [comment]
So it seems that the priors for those are off the plotting x-scale.. Do you want me to come up with a way to see them and compress the posterior ? If so, you would need to show two plots, one with the posterior in full (what we have now) and one with the priors in full scale (would have to be coded).

**Comment by jaclyncleary** [comment]
I think that for now we leave the plots as-is and we can produce the plot using iscam-gui for this case.

**Comment by Shawkshaw** [comment]
Here are the HG AM1/AM2 gui posterior/prior plots:
AM2
![am2](https://user-images.githubusercontent.com/6414082/31519094-260185dc-af56-11e7-91ca-05b25e9adda2.png)

AM1
![am1](https://user-images.githubusercontent.com/6414082/31519095-262f5476-af56-11e7-8749-5b23c5461e30.png)

**Comment by Shawkshaw** [comment]
I am not sure why these look different than the ones produced in the res doc for AM2, I used the same file...
![figure31hgam2](https://user-images.githubusercontent.com/6414082/31519846-9b84b494-af58-11e7-91bc-1f1c82ebf533.png)

![hgam1](https://user-images.githubusercontent.com/6414082/31519845-9b37209e-af58-11e7-8565-9e6f7c9a3254.png)

**Comment by cgrandin** [comment]
The plotting code is bit different.. I'll take a closer look tomorrow, have to leave here by 3

**Comment by jaclyncleary** [comment]
@cgrandin Can you also see why the MPD values are not plotted on ln(q1) and ln(q2)?

**Comment by cgrandin** [comment]
The code for the ones in the document is newer and correct. I double checked the values in the mcmc and report files to make sure.

The reason the q1, q2, and M MPDs are not in the plot is because I forgot to log them first.

**Comment by grinnellm** [comment]
I'm trying to bring these plots into our presentation dynamically. I was successful with AM2 using the code
> <<hg.priors2>>=
> make.priors.posts.plot(hg.b, priors.only=FALSE)
> @

I tried to generate the same plot for AM1 by substituting `hg.a` for `hg.b`, but I got an error:
`object 'hg.a' not found`

**Comment by Shawkshaw** [comment]
try hg.am1? this worked for the decision tables

**Comment by grinnellm** [comment]
Genius! Thanks Sarah. Is the `hg.b` part correct (i.e., it's HG AM2)?

**Comment by Shawkshaw** [comment]
yup

**Comment by cgrandin** [comment]
Yes.. all those are defined in custrom-knitr-variables.r
You can also see the sensitivity list definitions there.
In retrospect I should have called it hg.am2 but we've come too far.. :)

**Comment by jaclyncleary** [comment]
@cgrandin 
What I still don't understand is why we don't see the prior being plotted for AM2: q1 and q2, and for AM1: q1.  The scales are more or less the same and I would expect to see the prior partially plotted as it is in the gui. Help.

While the question still remains in my mind, I'm going to use the tabular q-values rather than attempt to use the distribution plots. (for the presentation)

**Comment by cgrandin** [comment]
I've found the bug.. just fixing it now

**Comment by grinnellm** [comment]
Do we need to `delete.rdata.files()` and `build()`?

**Comment by cgrandin** [comment]
fixed in commit 4f9170ea59509df8deb92c5e635f348e7a4957fc. 
q1 for AM2 will still not show anything because it is an uninformative prior (no prior)!
Glad to have this one fixed.

No Matt - just build the doc again!
