### ISSUE TITLE
needing prior prob distributions with posterior histograms for AM1 base for all 5 stocks

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#81]
I notice that we don't have a version of Fig 83 for AM1, estimate time varying M (i.e. the base).

@cgrandin Can you produce these as a separate PDF, or, add them in as the final 5 figures? I don't want to change any of the figure numbers before the meeting. Thx.

**Comment by cgrandin** [comment]
Yes, I'll get to it Thursday or tomorrow at lunch

**Comment by cgrandin** [comment]
[herring-2017-tvm-priors-am1.pdf](https://github.com/cgrandin/csas-latex/files/1373470/herring-2017-tvm-priors-am1.pdf)

**Comment by cgrandin** [comment]
Note this is for the models like CC-natural-mortality/AM1_timevaryingM. I re-read your note and now think you want the AM1 models for the base runs, i.e. CC/AM1 etc. Is that right?

**Comment by jaclyncleary** [comment]
what you posted is AM1 model with time-varying natural mortality and this is what I needed :)
