### ISSUE TITLE
I pushed beamer template

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/csas-latex#83]
I pushed a beamer template based on our hake ones. They are quite nice with dots you can press to navigate back and such. I added a two-column frame so you can see how to show a bulleted list beside a plot. 

I noticed after doing this that Matt had started his own, I'll leave it up to you which look you like better, or if some combination of the two works for you.
Cheers!

**Comment by grinnellm** [comment]
I'm trying to bring in a decision table. I added another slide to your example "beamer-herring-assessment.rnw":

\frame{\frametitle{Decision table for HG AM2}
<<hg.decision.table, results='asis', echo=FALSE>>=
dec.table.font.size <- 12
dec.table.font.space <- 13
cap <- paste0("Probabilistic decision table for Haida Gwaii, AM2 model.")
make.decision.table(hg.b,
                    xcaption = cap,
                    xlabel = "tab:hg-am2-decision",
                    font.size = dec.table.font.size,
                    space.size = dec.table.font.space,
                    placement = "H")
@
}

But it's not working. Any idea why?

**Comment by cgrandin** [comment]
I've solved this but just trying to change the font size so that it fits. I'll be pushing soon

**Comment by cgrandin** [comment]
Done in commit e913c89b89d9a82e723c117d28d7469a47da3cca

**Comment by cgrandin** [comment]
You could put the code chunks for all the tables in the beamer presentation now that they will work.. It would be better in the sense that you wouldn't have to worry about forgetting to re-make the tables into pngs like how it is now.. Just a suggestion

**Comment by jaclyncleary** [comment]
thanks Chris. I'll leave this to Matt to decide. He's off today but back in tomorrow...
