### ISSUE TITLE
why when I open the res-doc.pdf through Rstudio do I get a clickable pdf, but not when I open the same doc in Adobe?

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#85]
Ie, in Adobe I can't click Figure 8 and jump to Fig 8

**Comment by cgrandin** [comment]
Something's not set up right in your Adobe app I think.. Send me your pdf and I'll take a look, I have adobe Acrobat DC pro

**Comment by grinnellm** [comment]
Are you looking at the PDF sent out by the CSAS office? I get a clickable PDF in Adobe when I open the res-doc that we made, but not the one sent out by the CSAS office.  Maybe they `improved' it by removing the hyperlinks?

**Comment by jaclyncleary** [comment]
yup that's it.
