### ISSUE TITLE
help with interpreting PRD retro plots

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#86]
I don't understand what's happening with PRD retro plots. Specifically why is the retro-4 (2014). Fig 10b shows a high number of age-2s in 2014, but the survey index barely changes from 2013 to 2014 and the estimated spawning biomass is constant through that time (Fig10a).

[PRD AM2.docx](https://github.com/cgrandin/csas-latex/files/1377293/PRD.AM2.docx)

**Comment by cgrandin** [comment]
I think the high recruitment in the end year (2014) is driving the model. It might be worth running the retrospective back 15 years to 2002 for PRD, where there is a similar large recruitment in the end year and similar survey index pattern to see if the model behaves the same way. You could do it in iscam-gui just to have a look

**Comment by Shawkshaw** [comment]
I reran the -retro 4 and double checked the input files and have not found anything wrong with this run.  
I ran the retro -15 and the sbt does not shoot up to the 40s in the last year like it does for -4 and recdevs do not shoot up either.

I will keep looking for what is making the 2013/2014 years go up so much...

![recdevs retro 4_15 prd](https://user-images.githubusercontent.com/6414082/31508855-40b29e74-af34-11e7-88d9-9632a8307935.png)

![sbt prd -15](https://user-images.githubusercontent.com/6414082/31509074-fe269334-af34-11e7-9f08-7cae9f8fc344.png)

**Comment by jaclyncleary** [comment]
Sarah- can you post PRD retro-15 for both AM1 and AM2? I'd like to have it as a slide and I think we'll want to add the retro-15 to the resdoc IN PLACE OF the retro-10 for PRD. Thx.

**Comment by Shawkshaw** [comment]
I updated these into the Herring repo retrospectives folder

**Comment by cgrandin** [comment]
I'll have to modify the build() code so that it brings this in. I'll let you know when it's done.

**Comment by cgrandin** [comment]
Ok, the switch has been made in commit 1214d75b233a2588f415cd86af71c21d361312e0. You need to copy the 15 folder over and then:
`source("all.r");build(ovwrt.retro=TRUE)`
and when you build the doc, the PRD plots will have changed.

I struggle to see why the recruitment is so large in the last year. I checked all the parameter outputs and there are no other major differences between retrospectives.

**Comment by Shawkshaw** [comment]
I added the -retro 11-14 runs for PRD AM1 and AM2 to the Herring repo.  
Jaclyn, did you want these added to the plots as well or did you just want to look at them?

**Comment by jaclyncleary** [comment]
please add them to the plots

**Comment by cgrandin** [comment]
I can do it.. just working on the prior/post plots first

**Comment by cgrandin** [comment]
Done in commit 95c1432beaf318b53e6edbe1fb9b174ac87ccd0c.

Once you copy the folders 11-15 in, you'll have to run build(). Don't worry it's fast since it's just the new retros.

I think I'll try to improve the legends so they don't cover up all the action.

**Comment by cgrandin** [comment]
Legends are much better. I also expanded the y scale so you can see more of what's going on.
Commit c14dab812ee936b6901445d9ef58827c76ff2aa1
