### ISSUE TITLE
Table 48

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#89]
I just realized that for table 48, there are twice as many rows as we need. Rows 1 and 2 are identical, same with 3 and 4, 5 and 6, etc.

Is it possible to simplify this table by deleting "survey" column and delete every 2nd row?

**Comment by cgrandin** [comment]
Yes no problem I'll change it

**Comment by cgrandin** [comment]
Done in commit 82318dd840f7509062610349320fa1425f9f12dc
