### ISSUE TITLE
Generate production plots for herring

### ISSUE THREAD

**Issue by grinnellm** [cgrandin/csas-latex#9]
Tweak Rob's R code to generate production plots using iSCAM V2 output.

**Comment by jaclyncleary** [comment]
have you managed to get Rob's code to run?

**Comment by jaclyncleary** [comment]
For the WP, I think it would be easiest to reproduce the SAR figs, for AM1 and AM2, all 5 stocks
![sar lrp fig](https://user-images.githubusercontent.com/2219398/30653880-2ba6e972-9de1-11e7-9141-41bc09f03a0b.png)

**Comment by grinnellm** [comment]
No, I haven't managed to run it yet -- I think it's looking for some data files that aren't in the DropBox folder. The data files will have new names now too. I haven't spent much time on this yet though; I was going to work on it today. It looks like panels (a) and (b) are repeats from the storyboard. What do you think about adding panels (c) and (d) from this figure to the storyboard? This would avoid duplication, which could be good in this already lengthy document.

**Comment by grinnellm** [comment]
Got it to run! On V1 data..

**Comment by grinnellm** [comment]
Panels (a) and (b) show the entire time series, but panels (c) and (d) show the Dive period only -- just confirming that's what you want.

**Comment by jaclyncleary** [comment]
yes, this is what I want :)

**Comment by grinnellm** [comment]
Roger.
Data for these plots comes from *.rep files. I'm unfamiliar with the contents, and some of the object names seem to have changed. Are the following assumptions correct?
- The variable `it` is now called `it_hat`.
- The variable `obs_ct` is now called `dCatchData`, and it's been transposed.
- The variable `M_tot` is now called `M`.
- The variable `ut2` is now called `ut`, and it's a matrix where column sums are equal to `ut2`.

**Comment by Shawkshaw** [comment]
•The variable  it  **is now the second column in the matrix d3_survey_data and its been transposed and pit in V1 = it_hat in V2** 
•The variable  obs_ct  is now called  dCatchData , and it's been transposed in the **last column of this matrix**
•The variable  M_tot  is now called  M.- **YES**
•The variable  ut2  is now called  ut , and it's a matrix where column sums are equal to  ut2 . **-YES both are equal to 1-exp(-colsum(ft))**
