### ISSUE TITLE
Likelihood table

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/csas-latex#90]
Make a likelihood table to address the reviewer's comments. It should include:

1. total likelihood values
2. differences in likelihood from the base model
3. AIC values

for the M sensitivity cases

**Comment by cgrandin** [comment]
After much investigation into the iscam code and outputs I believe this to be correct. The number of M parameters is 12 when m estimation is turned on. 
[herring-likelihoods-m-2017.pdf](https://github.com/cgrandin/csas-latex/files/1389439/herring-likelihoods-m-2017.pdf)

**Comment by cgrandin** [comment]
I could add AM1 if necessarry

**Comment by jaclyncleary** [comment]
This is what I expected to see. Yes pls for adding AM1--  I think if it's needed with the review, then both base runs would be requested.

**Comment by cgrandin** [comment]
[herring-likelihood-table-2017.pdf](https://github.com/cgrandin/csas-latex/files/1389482/herring-likelihood-table-2017.pdf)

**Comment by cgrandin** [comment]
fyi - The difference from AM1 to AM2 likelihoods are not zero, but to the second decimal place they are. I could report more significant figures in the table if you think it's necessary.

**Comment by jaclyncleary** [comment]
I don't think extra sig figs are needed,
and,

well I guess it brings up a question for me, what does "differences in likelihood from the base model" mean?

**Comment by cgrandin** [comment]
It means likelihood in base mode (AM2) - likelihood in current model

You can do the math by looking at the likelihood column if you want

**Comment by cgrandin** [comment]
I changed it to say "difference from AM2"

**Comment by jaclyncleary** [comment]
**likelihood in base mode - likelihood in current model** makes sense because base changes - it's either AM1 TVM or AM2 TVM. So I think column header should stay as it was.

**Comment by cgrandin** [comment]
Roger that, I'll revert in  a bit

**Comment by jaclyncleary** [comment]
Interpretation:
Do you understand what + vs - "difference in likelihood from base" signals? I feel like I need to sit down with this and with you before I'd feel comfortable explaining this...

**Comment by Shawkshaw** [comment]
Do we want to add this table at the very end then? and take it out of the sensitivity analysis section?

**Comment by jaclyncleary** [comment]
yes

**Comment by cgrandin** [comment]
Well the goal of Maximum likelihood is to maximize the likelihood value. So bigger is better. In the case of the SOG, you can see that the constant M case is substantially lower (645 likelihood units less). I would interpret this as the model getting stuck in a "hole" in the the multivariate parameter space during the minimization. The rest appear to be close in value and I would suggest that overall the time-varying models are better, especially after looking at some of the other diagnostics.

**Comment by cgrandin** [comment]
Also include component likelihoods

Need to remove the penalties on fishery selectivity (lambda_1, 2, and 3) in iscam and re-run the MLEs for all M sensitivities.

**Comment by cgrandin** [comment]
Confirmed that none of lambda_1, lambda_2, or lambda_3 are being used for the herring model. Good news, we shouldn't have to re-run the model MLEs

**Comment by jaclyncleary** [comment]
have you figure out how to remove the penalties from the likelihood components?

**Comment by cgrandin** [comment]
They were all removed already. I used the debugger to confirm that. So I am just putting the likelihood components into the table now.

**Comment by cgrandin** [comment]
Done in commit c185848bcd5cb7d821ac981be4d0f4ae59aa33a7
