### ISSUE TITLE
Retrospective plots missing in presentation

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/csas-latex#93]
Maybe you know this but I noticed they are not in there yet (slide 52). I didn't add them since I don't know if someone was working on this. I can if it you want.

**Comment by Shawkshaw** [comment]
Hi Chris, 
I was trying to add SOG and PRD but could not get SOG to work and the PRD was only showing the -1 to -9 and -15 plots?  Any ideas?
Thanks!

**Comment by cgrandin** [comment]
I can add them :)
