### ISSUE TITLE
Trouble adding Tables 13-17

### ISSUE THREAD

**Issue by Shawkshaw** [cgrandin/csas-latex#96]
I am getting this error in the pdf ## Error in x[[jj]][iseq] <- vjj: replacement has length zero

**Comment by cgrandin** [comment]
Go ahead and commit it as you have it and I'll fix the error

**Comment by cgrandin** [comment]
Actually I can just add them.. I see where you're going with it

**Comment by cgrandin** [comment]
So after a bunch of trying to add them I see they are already in there starting at slide 64!

**Comment by Shawkshaw** [comment]
Do these print out in the pdf for you?  In mine I am still getting the error
 ## Error in x[[jj]][iseq] <- vjj: replacement has length zero 
It may just be mine though as this has happened for other tables in the resdoc for me...

**Comment by cgrandin** [comment]
No.. have you re-sourced Matt's stuff?

**Comment by Shawkshaw** [comment]
I thought I had but I will try again:)

**Comment by jaclyncleary** [comment]
works for me in the presentation.pdf

**Comment by cgrandin** [comment]
Are you still having trouble Sarah?

**Comment by Shawkshaw** [comment]
No it is working now:) thx
