### ISSUE TITLE
update: 940pm...

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#97]
I have a few edits that I will make to text on slides but I think changes that need the assistance of the 3 of you are done. Thanks so much for all your help.

I'm still not getting Table 44 but I will now attempt (again) a complete clean and resource.

Matt- the final pdf on memory stick may need to come from you.

**Comment by cgrandin** [comment]
Ok, I'm going to sign off for the night.. I can also build everything in the morning if necessary..
