### ISSUE TITLE
Add age comp fit plots

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/csas-latex#98]
From reviewer request - either observed/expected for every year (lots of figs) or a one-to-one plot or residual bubble plots (we have the code for this).

**Comment by jaclyncleary** [comment]
yes to starting with one-to-one plot

**Comment by cgrandin** [comment]
How about residuals bubble plots instead?

**Comment by cgrandin** [comment]
I think this is probably good enough for tomorrow...
[herring-age-fit-residuals.pdf](https://github.com/cgrandin/csas-latex/files/1393274/herring-age-fit-residuals.pdf)

I think they are OK. I don't see any patterns

**Comment by cgrandin** [comment]
Blue points represent zero samples, red are positive residuals, and black are negative residuals.

**Comment by cgrandin** [comment]
This is better... the actual fits as well. Sorry about the SOG one but It's late in the day!!!
[herring-age-comp-fits-and-residuals.pdf](https://github.com/cgrandin/csas-latex/files/1393320/herring-age-comp-fits-and-residuals.pdf)

**Comment by cgrandin** [comment]
Should I add these to the assessment. If I recall that was what was suggested.

**Comment by jaclyncleary** [comment]
confirmed: please add

**Comment by cgrandin** [comment]
Added in commit 7c5ed95695a7a9447876bd2fb1b7667049fe44bd
